### ISSUE TITLE
Try to use 'libudev.so.1' when find_library returns None

### ISSUE THREAD

**Issue by afazekas** [pyudev/pyudev#108] opened 2015-10-13 08:10 UTC
I have very minimal Linux system where I tried to use pyudev .

ctypes.util.find_library() fails to find the library because non of the tools was enabled for have find_library() working. because pyudev would be the only library which needs find_library working, I would like to ask you to
Instead of giving up when find_library() returns None, pyudev should try to use the most frequently used library name(s), for example 'libudev.so.1 '

Here is how my system behaves:
    / # ldconfig -p
    Library cache disabled
    / # python
    Python 2.7.10 (default, Oct 12 2015, 21:03:56) 
    [GCC 4.9.3] on linux2
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import ctypes.util
    >>> print ctypes.util.find_library('udev')
    None
    >>> ctypes.CDLL('libudev.so', use_errno=True)
    &lt;CDLL 'libudev.so', handle 8a86af0 at f742ff8c&gt;
    >>> 
    >>> ctypes.CDLL('libudev.so.1', use_errno=True)
    &lt;CDLL 'libudev.so.1', handle 8a92928 at f742f64c&gt;

Edit:
For 'c' the 'libc.so.1' could be used for having the pipe2 syscall, but the auto fall back to pipe() is working without this.

**Comment by mulkieran** [comment] 2015-10-13 16:33
The reason for using ```find_library``` is platform independence. So, it's probably wrong to hard-code platform specific fall-backs. It is possible that some sort of user setting would work. What does ```find_library``` depend on that is missing on your system?

**Comment by afazekas** [comment] 2015-10-14 14:58
find_library() is  using the `ldconfig -p` in the background for searching libraries this is not available on my system. The image is cross compiled, so most of the regular build tools will not be available at run time as well.

What I am actually trying to do, is create small initramfs image with https://github.com/openstack/ironic-python-agent installed.

I am using uClibc with the default config, so at the end I do not have /etc/ld.so.cache .
Adding a small fallback code leads to smaller image, than trying to make find_library() providing the usual answer.

```diff
diff --git a/src/pyudev/_libudev.py b/src/pyudev/_libudev.py
index a0de8fb..5499dd0 100644
--- a/src/pyudev/_libudev.py
+++ b/src/pyudev/_libudev.py
@@ -263,11 +263,14 @@ def load_udev_library():
     Important functions are given proper signatures and return types to
     support type checking and argument conversion.
 
-    Raise :exc:`~exceptions.ImportError`, if the udev library was not found.
+    Raise :exc:`~exceptions.OSError`, if the udev library was not found.
     """
     udev_library_name = find_library('udev')
     if not udev_library_name:
-        raise ImportError('No library named udev')
+        # ctypes.find_library does not works on small systems
+        # (for example without ld.so.cache).
+        # We will try to most frequently used name as a last chance
+        udev_library_name = 'libudev.so.1'
     libudev = CDLL(udev_library_name, use_errno=True)
     # context function signature
     for namespace, members in SIGNATURES.items():
```

**Comment by mulkieran** [comment] 2015-10-15 12:13
If ```find_library``` isn't working then it can  not find libc any more than it can find libudev. This is  less likely to cause a problem, as the only purpose of libc is to provide a pipe implementation if Python doesn't and that is only necessary for monitor. However, it seems like some consistency in handling these two situations is desirable.

**Comment by mulkieran** [comment] 2015-10-15 12:22
This is related to #83. In #83 the library is not found because it doesn't match what ```find_library``` thinks is the requirement, apparently.

**Comment by mulkieran** [comment] 2016-05-23 12:19
The handling of SIGNATURES in libudev is more complex than that lin libc, but possibly for no good reason. Perhaps if libudev.SIGNATURES is flattened, the whole thing can be made more uniform.

**Comment by mulkieran** [comment] 2016-05-24 13:43
This is officially a duplicate of #83 at this point. find_library is replete w/ problems, apparently.

**Closed by mulkieran** 2016-05-24 13:43 UTC
Labels: challenging, duplicate, enhancement
